<a href="https://colab.research.google.com/github/YogaSakti/naive-bayes/blob/master/naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# import librarry yang dibutuhkan
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [15]:
# Import data caesarian
caesarian = pd.read_csv("/content/caesarian.csv")

In [16]:
caesarian

Age  'Delivery number'  ...  'Heart Problem'  Caesarian
0    22                  1  ...                0          0
1    26                  2  ...                0          1
2    26                  2  ...                0          0
3    28                  1  ...                0          0
4    22                  2  ...                0          1
..  ...                ...  ...              ...        ...
75   27                  2  ...                0          0
76   33                  4  ...                0          1
77   29                  2  ...                0          1
78   25                  1  ...                0          1
79   24                  2  ...                0          0

[80 rows x 6 columns]

In [17]:
# melihat beberapa data awal
caesarian.head()

Age  'Delivery number'  ...  'Heart Problem'  Caesarian
0   22                  1  ...                0          0
1   26                  2  ...                0          1
2   26                  2  ...                0          0
3   28                  1  ...                0          0
4   22                  2  ...                0          1

[5 rows x 6 columns]

In [18]:
# melihat info dari data
caesarian.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  80 non-null     int64
 1   'Delivery number'    80 non-null     int64
 2   'Delivery time'      80 non-null     int64
 3   'Blood of Pressure'  80 non-null     int64
 4   'Heart Problem'      80 non-null     int64
 5   Caesarian            80 non-null     int64
dtypes: int64(6)
memory usage: 3.9 KB


In [19]:
# Variabel independen yaitu data selain caesarian
x = caesarian.drop(["Caesarian"], axis = 1)

In [20]:
# Variabel dependen yaitu caesarian saja
y = caesarian["Caesarian"]

In [21]:
# training data dengan random state 123 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [22]:
# melihat data test variable independen 
x_test

Age  'Delivery number'  ...  'Blood of Pressure'  'Heart Problem'
64   31                  1  ...                    2                1
58   26                  1  ...                    2                0
59   30                  2  ...                    2                1
4    22                  2  ...                    1                0
69   27                  2  ...                    0                0
53   35                  1  ...                    0                0
31   40                  1  ...                    1                1
77   29                  2  ...                    2                0
8    28                  2  ...                    1                0
43   22                  1  ...                    1                0
9    27                  1  ...                    1                0
37   31                  2  ...                    1                0
75   27                  2  ...                    1                0
29   26                  2  ...                    1                1
72   28                  2  ...                    1                0
79   24                  2  ...                    1                0

[16 rows x 5 columns]

In [23]:
# model klasifikasi naive bayes
modelnb = GaussianNB()

In [24]:
# masukkan data training pada model klasifikasi Naive Bayes
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([25., 39.])

In [25]:
# lakukan prediksi 
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [26]:
# bandingkan dengan dengan nilai testing yang sebenarnya 
np.array(y_test)

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0])

In [27]:
# mencari nilai probabilitas dari hasil prediksi
nbtrain.predict_proba(x_test)

array([[0.13322595, 0.86677405],
       [0.74653837, 0.25346163],
       [0.08698533, 0.91301467],
       [0.70519117, 0.29480883],
       [0.49123283, 0.50876717],
       [0.31283492, 0.68716508],
       [0.01726316, 0.98273684],
       [0.63383692, 0.36616308],
       [0.70894773, 0.29105227],
       [0.80047685, 0.19952315],
       [0.83623454, 0.16376546],
       [0.69456277, 0.30543723],
       [0.75275095, 0.24724905],
       [0.16209657, 0.83790343],
       [0.70894773, 0.29105227],
       [0.77505323, 0.22494677]])

In [33]:
# membuat Confussion Matrix
confusion_matrix(y_test, y_pred)

array([[5, 4],
       [5, 2]])

In [34]:
# tampilan Confusion Matrix yang lebih rapi
y_actual = pd.Series(np.array(y_test), name = "actual")
y_pred = pd.Series(y_pred, name = "prediction")
df_confusion = pd.crosstab(y_actual, y_pred)
df_confusion

prediction  0  1
actual          
0           5  4
1           5  2

In [31]:
# mencari nilai akurasi 
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.56      0.53         9
           1       0.33      0.29      0.31         7

    accuracy                           0.44        16
   macro avg       0.42      0.42      0.42        16
weighted avg       0.43      0.44      0.43        16

